/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EnrollResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Personality = IDL.Variant({
  'calm' : IDL.Null,
  'playful' : IDL.Null,
  'encouraging' : IDL.Null,
  'witty' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'personality' : Personality,
  'username' : IDL.Text,
  'messagesSent' : IDL.Nat,
  'badges' : IDL.Vec(IDL.Text),
  'streakDays' : IDL.Nat,
  'level' : IDL.Nat,
  'burnoutScore' : IDL.Nat,
  'lastActive' : IDL.Int,
  'completedTopics' : IDL.Vec(IDL.Text),
  'companionName' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const MockTestResult = IDL.Record({
  'id' : IDL.Text,
  'completedAt' : Timestamp,
  'timeSpentSecs' : IDL.Nat,
  'maxScore' : IDL.Nat,
  'domain' : IDL.Text,
  'userId' : IDL.Principal,
  'answers' : IDL.Vec(IDL.Nat),
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : IDL.Int,
  'timeTaken' : IDL.Nat,
  'testId' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const Article = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'views' : IDL.Nat,
  'authorId' : IDL.Principal,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
  'likes' : IDL.Nat,
  'dislikes' : IDL.Nat,
});
export const DirectMessage = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'read' : IDL.Bool,
  'receiverId' : IDL.Principal,
  'timestamp' : Timestamp,
  'senderId' : IDL.Principal,
});
export const Conversation = IDL.Record({
  'participants' : IDL.Vec(IDL.Principal),
  'lastMessage' : DirectMessage,
  'unreadCount' : IDL.Nat,
});
export const CourseId = IDL.Text;
export const Experience = IDL.Record({
  'id' : IDL.Text,
  'difficulty' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : IDL.Text,
  'authorName' : IDL.Text,
  'company' : IDL.Text,
  'experienceText' : IDL.Text,
});
export const Message = IDL.Record({
  'role' : IDL.Text,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'universityName' : IDL.Text,
  'username' : IDL.Text,
  'text' : IDL.Text,
  'timestamp' : Timestamp,
  'rating' : IDL.Nat,
});
export const Note = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'topicId' : IDL.Text,
});
export const ProgressReport = IDL.Record({
  'xp' : IDL.Nat,
  'username' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'quizzesPassedCount' : IDL.Nat,
  'streakDays' : IDL.Nat,
  'level' : IDL.Nat,
  'completedTopicsCount' : IDL.Nat,
  'enrolledCourses' : IDL.Vec(IDL.Text),
});
export const Question = IDL.Record({
  'topic' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'xpReward' : IDL.Nat,
  'answers' : IDL.Vec(IDL.Text),
  'difficulty' : IDL.Nat,
  'text' : IDL.Text,
});
export const HttpRequest = IDL.Record({
  'url' : IDL.Text,
  'method' : IDL.Text,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const HttpResponse = IDL.Record({
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'status_code' : IDL.Nat16,
});
export const AIChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
});
export const VerifyResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'addMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addSampleQuestions' : IDL.Func([], [], []),
  'awardBadge' : IDL.Func([IDL.Text], [], []),
  'awardGCoins' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'completeTopic' : IDL.Func([IDL.Text], [], []),
  'deleteNote' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'dislikeArticle' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'enrollCourse' : IDL.Func([IDL.Text], [EnrollResult], []),
  'followUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllStats' : IDL.Func([], [UserProfile], ['query']),
  'getAllTestResults' : IDL.Func([], [IDL.Vec(MockTestResult)], ['query']),
  'getArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getDomainTestResults' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MockTestResult)],
      ['query'],
    ),
  'getEnrolledCourses' : IDL.Func([], [IDL.Vec(CourseId)], ['query']),
  'getExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
  'getGCoins' : IDL.Func([], [IDL.Nat], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getLatestReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getMessages' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DirectMessage)],
      ['query'],
    ),
  'getMockTestResults' : IDL.Func([], [IDL.Vec(MockTestResult)], ['query']),
  'getMyFollowers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMyFollowing' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getOrCreateProfile' : IDL.Func([IDL.Text], [UserProfile], []),
  'getProgressReport' : IDL.Func([], [ProgressReport], ['query']),
  'getQuestionsByTopic' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getTestLeaderboard' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
  'incrementArticleView' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'isFollowingUser' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'likeArticle' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'markMessagesRead' : IDL.Func([IDL.Principal], [], []),
  'proxyAIChat' : IDL.Func([IDL.Vec(AIChatMessage), IDL.Text], [IDL.Text], []),
  'saveDomainTestResult' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat)],
      [IDL.Text],
      [],
    ),
  'saveMockTestResult' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text)],
      [MockTestResult],
      [],
    ),
  'saveNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Note], []),
  'sendDirectMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Text], []),
  'sendVerificationEmail' : IDL.Func([IDL.Text], [], []),
  'submitArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [Article],
      [],
    ),
  'submitExperience' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Experience],
      [],
    ),
  'submitReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : Review, 'err' : IDL.Text })],
      [],
    ),
  'unenrollCourse' : IDL.Func([IDL.Text], [EnrollResult], []),
  'unfollowUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateCompanion' : IDL.Func([IDL.Text, Personality], [], []),
  'updateNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Opt(Note)], []),
  'verifyEmail' : IDL.Func([IDL.Text, IDL.Text], [VerifyResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EnrollResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Personality = IDL.Variant({
    'calm' : IDL.Null,
    'playful' : IDL.Null,
    'encouraging' : IDL.Null,
    'witty' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'xp' : IDL.Nat,
    'personality' : Personality,
    'username' : IDL.Text,
    'messagesSent' : IDL.Nat,
    'badges' : IDL.Vec(IDL.Text),
    'streakDays' : IDL.Nat,
    'level' : IDL.Nat,
    'burnoutScore' : IDL.Nat,
    'lastActive' : IDL.Int,
    'completedTopics' : IDL.Vec(IDL.Text),
    'companionName' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const MockTestResult = IDL.Record({
    'id' : IDL.Text,
    'completedAt' : Timestamp,
    'timeSpentSecs' : IDL.Nat,
    'maxScore' : IDL.Nat,
    'domain' : IDL.Text,
    'userId' : IDL.Principal,
    'answers' : IDL.Vec(IDL.Nat),
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : IDL.Int,
    'timeTaken' : IDL.Nat,
    'testId' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const Article = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'views' : IDL.Nat,
    'authorId' : IDL.Principal,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
    'likes' : IDL.Nat,
    'dislikes' : IDL.Nat,
  });
  const DirectMessage = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'read' : IDL.Bool,
    'receiverId' : IDL.Principal,
    'timestamp' : Timestamp,
    'senderId' : IDL.Principal,
  });
  const Conversation = IDL.Record({
    'participants' : IDL.Vec(IDL.Principal),
    'lastMessage' : DirectMessage,
    'unreadCount' : IDL.Nat,
  });
  const CourseId = IDL.Text;
  const Experience = IDL.Record({
    'id' : IDL.Text,
    'difficulty' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : IDL.Text,
    'authorName' : IDL.Text,
    'company' : IDL.Text,
    'experienceText' : IDL.Text,
  });
  const Message = IDL.Record({
    'role' : IDL.Text,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'universityName' : IDL.Text,
    'username' : IDL.Text,
    'text' : IDL.Text,
    'timestamp' : Timestamp,
    'rating' : IDL.Nat,
  });
  const Note = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'topicId' : IDL.Text,
  });
  const ProgressReport = IDL.Record({
    'xp' : IDL.Nat,
    'username' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'quizzesPassedCount' : IDL.Nat,
    'streakDays' : IDL.Nat,
    'level' : IDL.Nat,
    'completedTopicsCount' : IDL.Nat,
    'enrolledCourses' : IDL.Vec(IDL.Text),
  });
  const Question = IDL.Record({
    'topic' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'xpReward' : IDL.Nat,
    'answers' : IDL.Vec(IDL.Text),
    'difficulty' : IDL.Nat,
    'text' : IDL.Text,
  });
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'status_code' : IDL.Nat16,
  });
  const AIChatMessage = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const VerifyResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    'addMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addSampleQuestions' : IDL.Func([], [], []),
    'awardBadge' : IDL.Func([IDL.Text], [], []),
    'awardGCoins' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'completeTopic' : IDL.Func([IDL.Text], [], []),
    'deleteNote' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'dislikeArticle' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'enrollCourse' : IDL.Func([IDL.Text], [EnrollResult], []),
    'followUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllStats' : IDL.Func([], [UserProfile], ['query']),
    'getAllTestResults' : IDL.Func([], [IDL.Vec(MockTestResult)], ['query']),
    'getArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getDomainTestResults' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MockTestResult)],
        ['query'],
      ),
    'getEnrolledCourses' : IDL.Func([], [IDL.Vec(CourseId)], ['query']),
    'getExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
    'getGCoins' : IDL.Func([], [IDL.Nat], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getLatestReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DirectMessage)],
        ['query'],
      ),
    'getMockTestResults' : IDL.Func([], [IDL.Vec(MockTestResult)], ['query']),
    'getMyFollowers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMyFollowing' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getOrCreateProfile' : IDL.Func([IDL.Text], [UserProfile], []),
    'getProgressReport' : IDL.Func([], [ProgressReport], ['query']),
    'getQuestionsByTopic' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getTestLeaderboard' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'incrementArticleView' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'isFollowingUser' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'likeArticle' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'markMessagesRead' : IDL.Func([IDL.Principal], [], []),
    'proxyAIChat' : IDL.Func(
        [IDL.Vec(AIChatMessage), IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveDomainTestResult' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat)],
        [IDL.Text],
        [],
      ),
    'saveMockTestResult' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text)],
        [MockTestResult],
        [],
      ),
    'saveNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Note], []),
    'sendDirectMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Text], []),
    'sendVerificationEmail' : IDL.Func([IDL.Text], [], []),
    'submitArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [Article],
        [],
      ),
    'submitExperience' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Experience],
        [],
      ),
    'submitReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : Review, 'err' : IDL.Text })],
        [],
      ),
    'unenrollCourse' : IDL.Func([IDL.Text], [EnrollResult], []),
    'unfollowUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateCompanion' : IDL.Func([IDL.Text, Personality], [], []),
    'updateNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(Note)],
        [],
      ),
    'verifyEmail' : IDL.Func([IDL.Text, IDL.Text], [VerifyResult], []),
  });
};

export const init = ({ IDL }) => { return []; };