/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIChatMessage { 'content' : string, 'role' : string }
export interface Article {
  'id' : string,
  'status' : string,
  'title' : string,
  'content' : string,
  'views' : bigint,
  'authorId' : Principal,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'authorName' : string,
  'likes' : bigint,
  'dislikes' : bigint,
}
export interface Conversation {
  'participants' : Array<Principal>,
  'lastMessage' : DirectMessage,
  'unreadCount' : bigint,
}
export type CourseId = string;
export interface DirectMessage {
  'id' : string,
  'content' : string,
  'read' : boolean,
  'receiverId' : Principal,
  'timestamp' : Timestamp,
  'senderId' : Principal,
}
export type EnrollResult = { 'ok' : null } |
  { 'err' : string };
export interface Experience {
  'id' : string,
  'difficulty' : string,
  'createdAt' : Timestamp,
  'role' : string,
  'authorName' : string,
  'company' : string,
  'experienceText' : string,
}
export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
  'status_code' : number,
}
export interface Message {
  'role' : string,
  'text' : string,
  'timestamp' : bigint,
}
export interface MockTestResult {
  'id' : string,
  'completedAt' : Timestamp,
  'timeSpentSecs' : bigint,
  'maxScore' : bigint,
  'domain' : string,
  'userId' : Principal,
  'answers' : Array<bigint>,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : bigint,
  'timeTaken' : bigint,
  'testId' : string,
  'percentage' : number,
}
export interface Note {
  'id' : string,
  'title' : string,
  'content' : string,
  'userId' : Principal,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'topicId' : string,
}
export type Personality = { 'calm' : null } |
  { 'playful' : null } |
  { 'encouraging' : null } |
  { 'witty' : null };
export interface ProgressReport {
  'xp' : bigint,
  'username' : string,
  'badges' : Array<string>,
  'quizzesPassedCount' : bigint,
  'streakDays' : bigint,
  'level' : bigint,
  'completedTopicsCount' : bigint,
  'enrolledCourses' : Array<string>,
}
export interface Question {
  'topic' : string,
  'correctIndex' : bigint,
  'xpReward' : bigint,
  'answers' : Array<string>,
  'difficulty' : bigint,
  'text' : string,
}
export interface Review {
  'id' : string,
  'universityName' : string,
  'username' : string,
  'text' : string,
  'timestamp' : Timestamp,
  'rating' : bigint,
}
export type Timestamp = bigint;
export interface UserProfile {
  'xp' : bigint,
  'personality' : Personality,
  'username' : string,
  'messagesSent' : bigint,
  'badges' : Array<string>,
  'streakDays' : bigint,
  'level' : bigint,
  'burnoutScore' : bigint,
  'lastActive' : bigint,
  'completedTopics' : Array<string>,
  'companionName' : string,
}
export type VerifyResult = { 'ok' : null } |
  { 'err' : string };
export interface _SERVICE {
  'addMessage' : ActorMethod<[string, string], undefined>,
  'addSampleQuestions' : ActorMethod<[], undefined>,
  'awardBadge' : ActorMethod<[string], undefined>,
  'awardGCoins' : ActorMethod<[bigint], bigint>,
  'completeTopic' : ActorMethod<[string], undefined>,
  'deleteNote' : ActorMethod<[string], boolean>,
  'dislikeArticle' : ActorMethod<[string], boolean>,
  'enrollCourse' : ActorMethod<[string], EnrollResult>,
  'followUser' : ActorMethod<[string], boolean>,
  'getAllStats' : ActorMethod<[], UserProfile>,
  'getAllTestResults' : ActorMethod<[], Array<MockTestResult>>,
  'getArticles' : ActorMethod<[string], Array<Article>>,
  'getConversations' : ActorMethod<[], Array<Conversation>>,
  'getDomainTestResults' : ActorMethod<[string], Array<MockTestResult>>,
  'getEnrolledCourses' : ActorMethod<[], Array<CourseId>>,
  'getExperiences' : ActorMethod<[], Array<Experience>>,
  'getGCoins' : ActorMethod<[], bigint>,
  'getHistory' : ActorMethod<[], Array<Message>>,
  'getLatestReviews' : ActorMethod<[bigint], Array<Review>>,
  'getMessages' : ActorMethod<[Principal], Array<DirectMessage>>,
  'getMockTestResults' : ActorMethod<[], Array<MockTestResult>>,
  'getMyFollowers' : ActorMethod<[], Array<string>>,
  'getMyFollowing' : ActorMethod<[], Array<string>>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getOrCreateProfile' : ActorMethod<[string], UserProfile>,
  'getProgressReport' : ActorMethod<[], ProgressReport>,
  'getQuestionsByTopic' : ActorMethod<[string], Array<Question>>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'getTestLeaderboard' : ActorMethod<
    [string, bigint],
    Array<[Principal, bigint]>
  >,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  'incrementArticleView' : ActorMethod<[string], boolean>,
  'isFollowingUser' : ActorMethod<[string], boolean>,
  'likeArticle' : ActorMethod<[string], boolean>,
  'markMessagesRead' : ActorMethod<[Principal], undefined>,
  'proxyAIChat' : ActorMethod<[Array<AIChatMessage>, string], string>,
  'saveDomainTestResult' : ActorMethod<
    [string, bigint, bigint, bigint, Array<bigint>],
    string
  >,
  'saveMockTestResult' : ActorMethod<
    [string, bigint, bigint, bigint, Array<string>],
    MockTestResult
  >,
  'saveNote' : ActorMethod<[string, string, string], Note>,
  'sendDirectMessage' : ActorMethod<[Principal, string], string>,
  'sendVerificationEmail' : ActorMethod<[string], undefined>,
  'submitArticle' : ActorMethod<
    [string, string, Array<string>, string],
    Article
  >,
  'submitExperience' : ActorMethod<
    [string, string, string, string, string],
    Experience
  >,
  'submitReview' : ActorMethod<
    [string, string, bigint, string],
    { 'ok' : Review } |
      { 'err' : string }
  >,
  'unenrollCourse' : ActorMethod<[string], EnrollResult>,
  'unfollowUser' : ActorMethod<[string], boolean>,
  'updateCompanion' : ActorMethod<[string, Personality], undefined>,
  'updateNote' : ActorMethod<[string, string, string], [] | [Note]>,
  'verifyEmail' : ActorMethod<[string, string], VerifyResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];