/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type VerifyResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface Review {
    id: string;
    universityName: string;
    username: string;
    text: string;
    timestamp: Timestamp;
    rating: bigint;
}
export type Timestamp = bigint;
export interface ProgressReport {
    xp: bigint;
    username: string;
    badges: Array<string>;
    quizzesPassedCount: bigint;
    streakDays: bigint;
    level: bigint;
    completedTopicsCount: bigint;
    enrolledCourses: Array<string>;
}
export interface MockTestResult {
    id: string;
    completedAt: Timestamp;
    timeSpentSecs: bigint;
    maxScore: bigint;
    domain: string;
    userId: Principal;
    answers: Array<bigint>;
    score: bigint;
    totalQuestions: bigint;
    timestamp: bigint;
    timeTaken: bigint;
    testId: string;
    percentage: number;
}
export interface Reaction {
    messageId: string;
    userId: Principal;
    emoji: string;
    timestamp: Timestamp;
}
export interface Story {
    id: string;
    expiresAt: Timestamp;
    viewerIds: Array<Principal>;
    authorId: Principal;
    createdAt: Timestamp;
    mediaUrl: string;
    viewCount: bigint;
    caption?: string;
    mediaType: string;
}
export type EnrollResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface DirectMessage {
    id: string;
    content: string;
    read: boolean;
    receiverId: Principal;
    timestamp: Timestamp;
    senderId: Principal;
}
export interface Conversation {
    participants: Array<Principal>;
    lastMessage: DirectMessage;
    unreadCount: bigint;
}
export interface ChallengeView {
    id: string;
    status: string;
    expiresAt: Timestamp;
    createdAt: Timestamp;
    challengeeScore?: bigint;
    quizTopic: string;
    challengerScore: bigint;
    quizId: string;
    challengee: string;
    challenger: string;
}
export interface Article {
    id: string;
    status: string;
    title: string;
    content: string;
    views: bigint;
    authorId: Principal;
    createdAt: Timestamp;
    tags: Array<string>;
    authorName: string;
    likes: bigint;
    dislikes: bigint;
}
export interface AIChatMessage {
    content: string;
    role: string;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface Experience {
    id: string;
    difficulty: string;
    createdAt: Timestamp;
    role: string;
    authorName: string;
    company: string;
    experienceText: string;
}
export interface HttpResponse {
    body: Uint8Array;
    headers: Array<HttpHeader>;
    status_code: number;
}
export interface Message {
    role: string;
    text: string;
    timestamp: bigint;
}
export type CourseId = string;
export interface Question {
    topic: string;
    correctIndex: bigint;
    xpReward: bigint;
    answers: Array<string>;
    difficulty: bigint;
    text: string;
}
export interface HttpRequest {
    url: string;
    method: string;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface UserProfile {
    xp: bigint;
    personality: Personality;
    username: string;
    messagesSent: bigint;
    badges: Array<string>;
    streakDays: bigint;
    level: bigint;
    burnoutScore: bigint;
    lastActive: bigint;
    completedTopics: Array<string>;
    companionName: string;
}
export interface Note {
    id: string;
    title: string;
    content: string;
    userId: Principal;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    topicId: string;
}
export enum MessageStatus {
    read = "read",
    sent = "sent",
    delivered = "delivered"
}
export enum Personality {
    calm = "calm",
    playful = "playful",
    encouraging = "encouraging",
    witty = "witty"
}
export interface backendInterface {
    addMessage(role: string, text: string): Promise<void>;
    addReaction(messageId: string, emoji: string): Promise<void>;
    addSampleQuestions(): Promise<void>;
    awardBadge(badgeId: string): Promise<void>;
    awardGCoins(amount: bigint): Promise<bigint>;
    checkSeasonalMilestone(domain: string, moduleIndex: bigint): Promise<string | null>;
    completeTopic(topicId: string): Promise<void>;
    createStory(mediaUrl: string, mediaType: string, caption: string | null): Promise<Story>;
    deleteNote(noteId: string): Promise<boolean>;
    deleteStory(storyId: string): Promise<void>;
    dislikeArticle(id: string): Promise<boolean>;
    enrollCourse(courseId: string): Promise<EnrollResult>;
    followUser(targetId: string): Promise<boolean>;
    getActiveChallenges(): Promise<Array<ChallengeView>>;
    getActiveStories(): Promise<Array<Story>>;
    getAllStats(): Promise<UserProfile>;
    getAllTestResults(): Promise<Array<MockTestResult>>;
    getArticles(status: string): Promise<Array<Article>>;
    getChallengeById(id: string): Promise<ChallengeView | null>;
    getChallengeHistory(): Promise<Array<ChallengeView>>;
    getConversations(): Promise<Array<Conversation>>;
    getDomainTestResults(domain: string): Promise<Array<MockTestResult>>;
    getEnrolledCourses(): Promise<Array<CourseId>>;
    getExperiences(): Promise<Array<Experience>>;
    getGCoins(): Promise<bigint>;
    getHistory(): Promise<Array<Message>>;
    getLatestReviews(limit: bigint): Promise<Array<Review>>;
    getMessageStatus(messageId: string): Promise<MessageStatus>;
    getMessages(otherUser: Principal): Promise<Array<DirectMessage>>;
    getMockTestResults(): Promise<Array<MockTestResult>>;
    getMyFollowers(): Promise<Array<string>>;
    getMyFollowing(): Promise<Array<string>>;
    getNotes(): Promise<Array<Note>>;
    getOrCreateProfile(username: string): Promise<UserProfile>;
    getProgressReport(): Promise<ProgressReport>;
    getQuestionsByTopic(topic: string): Promise<Array<Question>>;
    getReactions(messageId: string): Promise<Array<Reaction>>;
    getReviews(): Promise<Array<Review>>;
    getSavedMessages(): Promise<Array<string>>;
    getTestLeaderboard(domain: string, limit: bigint): Promise<Array<[Principal, bigint]>>;
    getUnlockedSeasonalItems(): Promise<Array<string>>;
    getUnreadCount(): Promise<bigint>;
    http_request(req: HttpRequest): Promise<HttpResponse>;
    incrementArticleView(id: string): Promise<boolean>;
    isFollowingUser(targetId: string): Promise<boolean>;
    likeArticle(id: string): Promise<boolean>;
    markDelivered(messageId: string): Promise<void>;
    markMessagesRead(otherUser: Principal): Promise<void>;
    proxyAIChat(messages: Array<AIChatMessage>, systemPrompt: string): Promise<string>;
    recordModuleCompletion(domain: string, moduleIndex: bigint): Promise<string | null>;
    removeReaction(messageId: string): Promise<void>;
    saveDomainTestResult(domain: string, score: bigint, maxScore: bigint, timeSpentSecs: bigint, answers: Array<bigint>): Promise<string>;
    saveMessage(messageId: string): Promise<void>;
    saveMockTestResult(testId: string, score: bigint, totalQuestions: bigint, timeTaken: bigint, answers: Array<string>): Promise<MockTestResult>;
    saveNote(title: string, content: string, topicId: string): Promise<Note>;
    sendChallenge(challengeeId: Principal, quizId: string, quizTopic: string, challengerScore: bigint): Promise<ChallengeView>;
    sendDirectMessage(receiverId: Principal, content: string): Promise<string>;
    sendVerificationEmail(email: string): Promise<void>;
    submitArticle(title: string, content: string, tags: Array<string>, authorName: string): Promise<Article>;
    submitChallengeScore(challengeId: string, score: bigint): Promise<boolean>;
    submitExperience(authorName: string, company: string, role: string, difficulty: string, experienceText: string): Promise<Experience>;
    submitReview(username: string, universityName: string, rating: bigint, text: string): Promise<{
        __kind__: "ok";
        ok: Review;
    } | {
        __kind__: "err";
        err: string;
    }>;
    unenrollCourse(courseId: string): Promise<EnrollResult>;
    unfollowUser(targetId: string): Promise<boolean>;
    unsaveMessage(messageId: string): Promise<void>;
    updateCompanion(name: string, personality: Personality): Promise<void>;
    updateNote(noteId: string, title: string, content: string): Promise<Note | null>;
    verifyEmail(email: string, code: string): Promise<VerifyResult>;
    viewStory(storyId: string): Promise<void>;
}
import type { ChallengeView as _ChallengeView, EnrollResult as _EnrollResult, MessageStatus as _MessageStatus, Note as _Note, Personality as _Personality, Review as _Review, Story as _Story, Timestamp as _Timestamp, UserProfile as _UserProfile, VerifyResult as _VerifyResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0, arg1);
            return result;
        }
    }
    async addReaction(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, arg1);
            return result;
        }
    }
    async addSampleQuestions(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSampleQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSampleQuestions();
            return result;
        }
    }
    async awardBadge(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.awardBadge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardBadge(arg0);
            return result;
        }
    }
    async awardGCoins(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.awardGCoins(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardGCoins(arg0);
            return result;
        }
    }
    async checkSeasonalMilestone(arg0: string, arg1: bigint): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkSeasonalMilestone(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkSeasonalMilestone(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeTopic(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTopic(arg0);
            return result;
        }
    }
    async createStory(arg0: string, arg1: string, arg2: string | null): Promise<Story> {
        if (this.processError) {
            try {
                const result = await this.actor.createStory(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Story_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStory(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Story_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteNote(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async deleteStory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStory(arg0);
            return result;
        }
    }
    async dislikeArticle(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.dislikeArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dislikeArticle(arg0);
            return result;
        }
    }
    async enrollCourse(arg0: string): Promise<EnrollResult> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollCourse(arg0);
                return from_candid_EnrollResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollCourse(arg0);
            return from_candid_EnrollResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async followUser(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getActiveChallenges(): Promise<Array<ChallengeView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveChallenges();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveChallenges();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveStories(): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveStories();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveStories();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStats(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStats();
                return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStats();
            return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTestResults(): Promise<Array<MockTestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestResults();
            return result;
        }
    }
    async getArticles(arg0: string): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticles(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticles(arg0);
            return result;
        }
    }
    async getChallengeById(arg0: string): Promise<ChallengeView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallengeById(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallengeById(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChallengeHistory(): Promise<Array<ChallengeView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallengeHistory();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallengeHistory();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations();
            return result;
        }
    }
    async getDomainTestResults(arg0: string): Promise<Array<MockTestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDomainTestResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDomainTestResults(arg0);
            return result;
        }
    }
    async getEnrolledCourses(): Promise<Array<CourseId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnrolledCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnrolledCourses();
            return result;
        }
    }
    async getExperiences(): Promise<Array<Experience>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExperiences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExperiences();
            return result;
        }
    }
    async getGCoins(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getGCoins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGCoins();
            return result;
        }
    }
    async getHistory(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistory();
            return result;
        }
    }
    async getLatestReviews(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestReviews(arg0);
            return result;
        }
    }
    async getMessageStatus(arg0: string): Promise<MessageStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageStatus(arg0);
                return from_candid_MessageStatus_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageStatus(arg0);
            return from_candid_MessageStatus_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: Principal): Promise<Array<DirectMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getMockTestResults(): Promise<Array<MockTestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockTestResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockTestResults();
            return result;
        }
    }
    async getMyFollowers(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFollowers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFollowers();
            return result;
        }
    }
    async getMyFollowing(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFollowing();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFollowing();
            return result;
        }
    }
    async getNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotes();
            return result;
        }
    }
    async getOrCreateProfile(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreateProfile(arg0);
                return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreateProfile(arg0);
            return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgressReport(): Promise<ProgressReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressReport();
            return result;
        }
    }
    async getQuestionsByTopic(arg0: string): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsByTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsByTopic(arg0);
            return result;
        }
    }
    async getReactions(arg0: string): Promise<Array<Reaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReactions(arg0);
            return result;
        }
    }
    async getReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews();
            return result;
        }
    }
    async getSavedMessages(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedMessages();
            return result;
        }
    }
    async getTestLeaderboard(arg0: string, arg1: bigint): Promise<Array<[Principal, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestLeaderboard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestLeaderboard(arg0, arg1);
            return result;
        }
    }
    async getUnlockedSeasonalItems(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnlockedSeasonalItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnlockedSeasonalItems();
            return result;
        }
    }
    async getUnreadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount();
            return result;
        }
    }
    async http_request(arg0: HttpRequest): Promise<HttpResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.http_request(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.http_request(arg0);
            return result;
        }
    }
    async incrementArticleView(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementArticleView(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementArticleView(arg0);
            return result;
        }
    }
    async isFollowingUser(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowingUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowingUser(arg0);
            return result;
        }
    }
    async likeArticle(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.likeArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeArticle(arg0);
            return result;
        }
    }
    async markDelivered(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markDelivered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markDelivered(arg0);
            return result;
        }
    }
    async markMessagesRead(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessagesRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessagesRead(arg0);
            return result;
        }
    }
    async proxyAIChat(arg0: Array<AIChatMessage>, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.proxyAIChat(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.proxyAIChat(arg0, arg1);
            return result;
        }
    }
    async recordModuleCompletion(arg0: string, arg1: bigint): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.recordModuleCompletion(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordModuleCompletion(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeReaction(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReaction(arg0);
            return result;
        }
    }
    async saveDomainTestResult(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: Array<bigint>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDomainTestResult(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDomainTestResult(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async saveMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMessage(arg0);
            return result;
        }
    }
    async saveMockTestResult(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: Array<string>): Promise<MockTestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMockTestResult(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMockTestResult(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async saveNote(arg0: string, arg1: string, arg2: string): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.saveNote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveNote(arg0, arg1, arg2);
            return result;
        }
    }
    async sendChallenge(arg0: Principal, arg1: string, arg2: string, arg3: bigint): Promise<ChallengeView> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChallenge(arg0, arg1, arg2, arg3);
                return from_candid_ChallengeView_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChallenge(arg0, arg1, arg2, arg3);
            return from_candid_ChallengeView_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendDirectMessage(arg0: Principal, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendDirectMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendDirectMessage(arg0, arg1);
            return result;
        }
    }
    async sendVerificationEmail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendVerificationEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendVerificationEmail(arg0);
            return result;
        }
    }
    async submitArticle(arg0: string, arg1: string, arg2: Array<string>, arg3: string): Promise<Article> {
        if (this.processError) {
            try {
                const result = await this.actor.submitArticle(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitArticle(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitChallengeScore(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitChallengeScore(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitChallengeScore(arg0, arg1);
            return result;
        }
    }
    async submitExperience(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Experience> {
        if (this.processError) {
            try {
                const result = await this.actor.submitExperience(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitExperience(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitReview(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<{
        __kind__: "ok";
        ok: Review;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2, arg3);
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2, arg3);
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async unenrollCourse(arg0: string): Promise<EnrollResult> {
        if (this.processError) {
            try {
                const result = await this.actor.unenrollCourse(arg0);
                return from_candid_EnrollResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unenrollCourse(arg0);
            return from_candid_EnrollResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async unfollowUser(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async unsaveMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsaveMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsaveMessage(arg0);
            return result;
        }
    }
    async updateCompanion(arg0: string, arg1: Personality): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompanion(arg0, to_candid_Personality_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompanion(arg0, to_candid_Personality_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateNote(arg0: string, arg1: string, arg2: string): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, arg1, arg2);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, arg1, arg2);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyEmail(arg0: string, arg1: string): Promise<VerifyResult> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyEmail(arg0, arg1);
                return from_candid_VerifyResult_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyEmail(arg0, arg1);
            return from_candid_VerifyResult_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async viewStory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.viewStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.viewStory(arg0);
            return result;
        }
    }
}
function from_candid_ChallengeView_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChallengeView): ChallengeView {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_EnrollResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnrollResult): EnrollResult {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_MessageStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageStatus): MessageStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Personality_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Personality): Personality {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Story_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Story): Story {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_VerifyResult_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerifyResult): VerifyResult {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChallengeView]): ChallengeView | null {
    return value.length === 0 ? null : from_candid_ChallengeView_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Note]): Note | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    personality: _Personality;
    username: string;
    messagesSent: bigint;
    badges: Array<string>;
    streakDays: bigint;
    level: bigint;
    burnoutScore: bigint;
    lastActive: bigint;
    completedTopics: Array<string>;
    companionName: string;
}): {
    xp: bigint;
    personality: Personality;
    username: string;
    messagesSent: bigint;
    badges: Array<string>;
    streakDays: bigint;
    level: bigint;
    burnoutScore: bigint;
    lastActive: bigint;
    completedTopics: Array<string>;
    companionName: string;
} {
    return {
        xp: value.xp,
        personality: from_candid_Personality_n14(_uploadFile, _downloadFile, value.personality),
        username: value.username,
        messagesSent: value.messagesSent,
        badges: value.badges,
        streakDays: value.streakDays,
        level: value.level,
        burnoutScore: value.burnoutScore,
        lastActive: value.lastActive,
        completedTopics: value.completedTopics,
        companionName: value.companionName
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    expiresAt: _Timestamp;
    viewerIds: Array<Principal>;
    authorId: Principal;
    createdAt: _Timestamp;
    mediaUrl: string;
    viewCount: bigint;
    caption: [] | [string];
    mediaType: string;
}): {
    id: string;
    expiresAt: Timestamp;
    viewerIds: Array<Principal>;
    authorId: Principal;
    createdAt: Timestamp;
    mediaUrl: string;
    viewCount: bigint;
    caption?: string;
    mediaType: string;
} {
    return {
        id: value.id,
        expiresAt: value.expiresAt,
        viewerIds: value.viewerIds,
        authorId: value.authorId,
        createdAt: value.createdAt,
        mediaUrl: value.mediaUrl,
        viewCount: value.viewCount,
        caption: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.caption)),
        mediaType: value.mediaType
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    expiresAt: _Timestamp;
    createdAt: _Timestamp;
    challengeeScore: [] | [bigint];
    quizTopic: string;
    challengerScore: bigint;
    quizId: string;
    challengee: string;
    challenger: string;
}): {
    id: string;
    status: string;
    expiresAt: Timestamp;
    createdAt: Timestamp;
    challengeeScore?: bigint;
    quizTopic: string;
    challengerScore: bigint;
    quizId: string;
    challengee: string;
    challenger: string;
} {
    return {
        id: value.id,
        status: value.status,
        expiresAt: value.expiresAt,
        createdAt: value.createdAt,
        challengeeScore: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.challengeeScore)),
        quizTopic: value.quizTopic,
        challengerScore: value.challengerScore,
        quizId: value.quizId,
        challengee: value.challengee,
        challenger: value.challenger
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    calm: null;
} | {
    playful: null;
} | {
    encouraging: null;
} | {
    witty: null;
}): Personality {
    return "calm" in value ? Personality.calm : "playful" in value ? Personality.playful : "encouraging" in value ? Personality.encouraging : "witty" in value ? Personality.witty : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    read: null;
} | {
    sent: null;
} | {
    delivered: null;
}): MessageStatus {
    return "read" in value ? MessageStatus.read : "sent" in value ? MessageStatus.sent : "delivered" in value ? MessageStatus.delivered : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Review;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Review;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Story>): Array<Story> {
    return value.map((x)=>from_candid_Story_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChallengeView>): Array<ChallengeView> {
    return value.map((x)=>from_candid_ChallengeView_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Personality_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Personality): _Personality {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Personality): {
    calm: null;
} | {
    playful: null;
} | {
    encouraging: null;
} | {
    witty: null;
} {
    return value == Personality.calm ? {
        calm: null
    } : value == Personality.playful ? {
        playful: null
    } : value == Personality.encouraging ? {
        encouraging: null
    } : value == Personality.witty ? {
        witty: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
